services:
  - type: web
    name: jana-birthday-api
    env: node
    buildCommand: npm install && npm run build && npm run migration:push
    startCommand: node dist/index.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_3Qp7gLKjIwdA@ep-wild-smoke-a5tisuij-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require
